apiVersion: v1
kind: ConfigMap
metadata:
  name: us-config
data:
  config.conf: |
    [Server]
    name = UserServer
    host = 0.0.0.0
    port = 8000

    [Cors]
    origins = ["*"]

    [Database]
    host = 10.0.0.59
    user = admin
    database = user_data
    pool_size = 10