apiVersion: v1
kind: ConfigMap
metadata:
  name: pe-config
data:
  config.conf: |
    [Cors]
    origins = ["*"]

    [Database]
    host = 10.0.0.59
    user = admin
    database = user_data
    pool_size = 10

    [Redis]
    host = 10.0.0.59
    port = 6379
    max_connections = 20

    [SQS]
    queue_url = https://sqs.ap-northeast-2.amazonaws.com/810648236112/PetDateUpdateQueue.fifo
    region = ap-northeast-2