# pe-svc.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pe
  name: pe-is
spec:
  type: ClusterIP
  selector:
    app: pe-pod  # 选择器：匹配Pod的标签
  ports:
  - port: 8001        # Service端口
    targetPort: 8001  # Pod内容器端口
