apiVersion: v1
kind: Secret
metadata:
  name: gs-config-secret
type: Opaque
stringData:  # 使用 stringData，K8s 会自动 base64 编码
  config-secret.conf: |
    [Database]
    password = aptx_4869

    [JWT]
    secret_key = your-64-char-super-secure-random-key-change-in-production
    algorithm = HS256
    refresh_token_expire_days = 7